Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -79,6 +79,31 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+          
+      - name: Search Dockerfiles and Build Images
+        run: |
+          BUILD_NUMBER=${{ github.run_number }}
+          echo "Build Number: $BUILD_NUMBER"
+          failures=0
+          find . -name "Dockerfile" -exec sh -c '
+            dir=$(dirname "{}")
+            image_name="ashish233001/microservices_$(basename $dir):'"$BUILD_NUMBER"'"
+            echo "Building Image: $image_name from directory: $dir"
+            if docker build -t $image_name $dir; then
+              echo "Pushing Image: $image_name"
+              docker push $image_name
+            else
+              echo "Failed to build: $image_name"
+              failures=$((failures+1))
+            fi
+          ' \;
+          
+          if [ $failures -gt 0 ]; then
+            echo "$failures builds failed!"
+            exit 1
+          else
+            echo "All Docker images built and pushed successfully!"
+          fi
 
       - name: Build and Push Docker Image
         run: |
